# Passo 1: Usar a imagem oficial do Node.js como base
FROM node:16

# Passo 2: Definir diretório de trabalho no container
WORKDIR /client

# Passo 6: Rodar o aplicativo React
CMD ["npm", "start"]

# Expor a porta 3000 para o React
EXPOSE 3000
