version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:5000
    depends_on:
      - api
    volumes:
      - ./client:/client
    networks:
      - app-network

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api/:/api
      - /api/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
